# Generated by Django 3.1.3 on 2020-11-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=60, max_digits=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('request_information', models.TextField(blank=True)),
            ],
        ),
    ]
