# Generated by Django 3.1.3 on 2020-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unica_app', '0002_numerohistorico_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerohistorico',
            name='ip',
            field=models.TextField(),
        ),
    ]
